import { MenuItem } from './types';

export const MENU_ITEMS: MenuItem[] = [
  {
    id: 'so1',
    name: 'Sukiyaki Black Soup',
    nameTh: 'สุกี้น้ำดำ',
    price: 0,
    category: 'Soup',
    type: 'Included',
    image: 'https://images.unsplash.com/photo-1607528971899-2e89e6c07787?w=800&auto=format&fit=crop&q=60',
    allergens: ['Soy'],
    isVegetarian: true,
    description: 'Sweet and savory Japanese black soup.',
    descriptionTh: 'ซุปน้ำดำญี่ปุ่นรสชาติหวานเค็มกลมกล่อม'
  },
  {
    id: 'so2',
    name: 'Original Soup',
    nameTh: 'ซุปต้นตำรับ',
    price: 0,
    category: 'Soup',
    type: 'Included',
    image: 'https://images.unsplash.com/photo-1548943487-a2e4e43b4853?w=800&auto=format&fit=crop&q=60',
    allergens: [],
    isVegetarian: true,
    description: 'Our signature light and refreshing original broth.',
    descriptionTh: 'ซุปต้นตำรับรสชาติเบาสบายและสดชื่น'
  },
  {
    id: 'so3',
    name: 'Pork Bone Soup',
    nameTh: 'ซุปกระดูกหมู',
    price: 0,
    category: 'Soup',
    type: 'Included',
    image: 'https://images.unsplash.com/photo-1594756202469-9ff9799b2e42?w=800&auto=format&fit=crop&q=60',
    allergens: [],
    isVegetarian: false,
    description: 'Rich and creamy pork bone broth.',
    descriptionTh: 'ซุปกระดูกหมูรสชาติเข้มข้นและกลมกล่อม'
  },
  {
    id: 'b1',
    name: 'A5 Wagyu Ribeye',
    nameTh: 'เนื้อวากิว A5 ริบอาย',
    price: 850,
    category: 'Meat',
    type: 'Add-on',
    image: 'https://images.unsplash.com/photo-1544025162-d76694265947?w=800&auto=format&fit=crop&q=60',
    allergens: [],
    isVegetarian: false,
    description: 'Premium Japanese A5 Wagyu with intense marbling.',
    descriptionTh: 'เนื้อวากิว A5 เกรดพรีเมียม ลายไขมันแทรกสวยงาม'
  },
  {
    id: 'm1',
    name: 'Kurobuta Pork Special',
    nameTh: 'หมูคุโรบุตะสเปเชียล',
    price: 0,
    category: 'Meat',
    type: 'Included',
    image: 'https://images.unsplash.com/photo-1602470520998-f4a52199a3d6?w=800&auto=format&fit=crop&q=60',
    allergens: [],
    isVegetarian: false,
    description: 'Special premium Kurobuta pork slices.',
    descriptionTh: 'หมูคุโรบุตะสไลด์เกรดพิเศษ'
  },
  {
    id: 'm2',
    name: 'Sliced Pork Collar',
    nameTh: 'สันคอหมูสไลซ์',
    price: 0,
    category: 'Meat',
    type: 'Included',
    image: 'https://images.unsplash.com/photo-1541529086526-db283c563270?w=800&auto=format&fit=crop&q=60',
    allergens: [],
    isVegetarian: false,
    description: 'Tender sliced pork collar.',
    descriptionTh: 'สันคอหมูสไลซ์นุ่มๆ'
  },
  {
    id: 'm3',
    name: 'Rolled Pork Belly',
    nameTh: 'หมูสามชั้นม้วน',
    price: 0,
    category: 'Meat',
    type: 'Included',
    image: 'https://images.unsplash.com/photo-1551135049-8a33b5883817?w=800&auto=format&fit=crop&q=60',
    allergens: [],
    isVegetarian: false,
    description: 'Thinly sliced rolled pork belly.',
    descriptionTh: 'หมูสามชั้นม้วนสไลด์บางๆ'
  },
  {
    id: 'm4',
    name: 'Marinated Pork',
    nameTh: 'หมูนุ่ม',
    price: 0,
    category: 'Meat',
    type: 'Included',
    image: 'https://images.unsplash.com/photo-1529692236671-f1f6cf9683ba?w=800&auto=format&fit=crop&q=60',
    allergens: [],
    isVegetarian: false,
    description: 'Tender marinated pork.',
    descriptionTh: 'หมูนุ่มหมักสูตรพิเศษ'
  },
  {
    id: 'm5',
    name: 'Marinated Chicken',
    nameTh: 'ไก่นุ่ม',
    price: 0,
    category: 'Meat',
    type: 'Included',
    image: 'https://images.unsplash.com/photo-1604503468506-a8da13d82791?w=800&auto=format&fit=crop&q=60',
    allergens: [],
    isVegetarian: false,
    description: 'Tender marinated chicken.',
    descriptionTh: 'ไก่นุ่มหมักสูตรพิเศษ'
  },
  {
    id: 'm6',
    name: 'Black Pepper Beef',
    nameTh: 'เนื้อวัวซอสพริกไทยดำ',
    price: 0,
    category: 'Meat',
    type: 'Included',
    image: 'https://images.unsplash.com/photo-1516684669134-de6f7c473a2a?w=800&auto=format&fit=crop&q=60',
    allergens: [],
    isVegetarian: false,
    description: 'Beef marinated in black pepper sauce.',
    descriptionTh: 'เนื้อวัวหมักซอสพริกไทยดำรสเข้มข้น'
  },
  {
    id: 'm7',
    name: 'Black Pepper Marinated Pork',
    nameTh: 'เนื้อหมูหมักซอสพริกไทยดำ',
    price: 0,
    category: 'Meat',
    type: 'Included',
    image: 'https://images.unsplash.com/photo-1516684732162-798a0062be99?w=800&auto=format&fit=crop&q=60',
    allergens: [],
    isVegetarian: false,
    description: 'Pork marinated in black pepper sauce.',
    descriptionTh: 'เนื้อหมูหมักซอสพริกไทยดำรสเข้มข้น'
  },
  {
    id: 'm8',
    name: 'Sliced Beef',
    nameTh: 'เนื้อวัวสไลซ์',
    price: 0,
    category: 'Meat',
    type: 'Included',
    image: 'https://images.unsplash.com/photo-1544025162-d76694265947?w=800&auto=format&fit=crop&q=60',
    allergens: [],
    isVegetarian: false,
    description: 'Fresh beef slices.',
    descriptionTh: 'เนื้อวัวสดสไลด์'
  },
  {
    id: 'm9',
    name: 'Minced Chicken with Shiitake',
    nameTh: 'ไก่บดเห็ดหอม',
    price: 0,
    category: 'Meat',
    type: 'Included',
    image: 'https://images.unsplash.com/photo-1606728035253-49df8bb63084?w=800&auto=format&fit=crop&q=60',
    allergens: [],
    isVegetarian: false,
    description: 'Minced chicken mixed with shiitake mushrooms.',
    descriptionTh: 'ไก่บดผสมเห็ดหอมปรุงรส'
  },
  {
    id: 'm10',
    name: 'Fish Tofu',
    nameTh: 'เต้าหู้เนื้อปลา',
    price: 0,
    category: 'Meat',
    type: 'Included',
    image: 'https://images.unsplash.com/photo-1512058564366-18510be2db19?w=800&auto=format&fit=crop&q=60',
    allergens: ['Fish'],
    isVegetarian: false,
    description: 'Soft and bouncy fish tofu.',
    descriptionTh: 'เต้าหู้เนื้อปลานุ่มเด้ง'
  },
  {
    id: 'm11',
    name: 'Seasoned Seaweed',
    nameTh: 'สาหร่ายทรงเครื่อง',
    price: 0,
    category: 'Meat',
    type: 'Included',
    image: 'https://images.unsplash.com/photo-1534422298391-e4f8c170db76?w=800&auto=format&fit=crop&q=60',
    allergens: ['Soy'],
    isVegetarian: false,
    description: 'Seasoned seaweed wrap with minced meat.',
    descriptionTh: 'สาหร่ายทรงเครื่องไส้เนื้อสับ'
  },
  {
    id: 'm12',
    name: 'Ping Pong Fish Balls',
    nameTh: 'ลูกชิ้นปิงปอง',
    price: 0,
    category: 'Meat',
    type: 'Included',
    image: 'https://images.unsplash.com/photo-1599481238505-b8b0537a3f77?w=800&auto=format&fit=crop&q=60',
    allergens: ['Fish'],
    isVegetarian: false,
    description: 'Classic bouncy fish balls.',
    descriptionTh: 'ลูกชิ้นปลาเด้งดึ๋ง'
  },
  {
    id: 'm13',
    name: 'Crab Stick',
    nameTh: 'ปูอัด',
    price: 0,
    category: 'Meat',
    type: 'Included',
    image: 'https://images.unsplash.com/photo-1553621042-f6e147245754?w=800&auto=format&fit=crop&q=60',
    allergens: ['Fish'],
    isVegetarian: false,
    description: 'Premium crab sticks.',
    descriptionTh: 'ปูอัดเกรดพรีเมียม'
  },
  {
    id: 'm14',
    name: 'Chicken Egg',
    nameTh: 'ไข่ไก่',
    price: 0,
    category: 'Meat',
    type: 'Included',
    image: 'https://images.unsplash.com/photo-1582722872445-44dc5f7e3c8f?w=800&auto=format&fit=crop&q=60',
    allergens: ['Egg'],
    isVegetarian: false,
    description: 'Fresh chicken egg.',
    descriptionTh: 'ไข่ไก่สด'
  },
  {
    id: 'm15',
    name: 'Egg Tofu',
    nameTh: 'เต้าหู้ไข่',
    price: 0,
    category: 'Meat',
    type: 'Included',
    image: 'https://images.unsplash.com/photo-1584263347416-85a18a45d449?w=800&auto=format&fit=crop&q=60',
    allergens: ['Egg'],
    isVegetarian: false,
    description: 'Soft egg tofu.',
    descriptionTh: 'เต้าหู้ไข่เนื้อนุ่ม'
  },
  {
    id: 's2',
    name: 'Hokkaido Scallops',
    nameTh: 'หอยเชลล์ฮอกไกโด',
    price: 520,
    category: 'Meat',
    type: 'Add-on',
    image: 'https://images.unsplash.com/photo-1599458252573-56ae36390329?w=800&auto=format&fit=crop&q=60',
    allergens: ['Shellfish'],
    isVegetarian: false,
    description: 'Sweet and succulent scallops from Hokkaido.',
    descriptionTh: 'หอยเชลล์รสหวานและนุ่มจากฮอกไกโด'
  },
  {
    id: 'v1',
    name: 'King Oyster Mushroom',
    nameTh: 'เห็ดนางรมหลวง',
    price: 0,
    category: 'Vegetable',
    type: 'Included',
    image: 'https://images.unsplash.com/photo-1591261730799-ee4e6c2d16d7?w=800&auto=format&fit=crop&q=60',
    allergens: [],
    isVegetarian: true,
    description: 'Premium meaty king oyster mushrooms.',
    descriptionTh: 'เห็ดนางรมหลวงเกรดพรีเมียม เนื้อแน่น'
  },
  {
    id: 'v2',
    name: 'Green Wakame Seaweed',
    nameTh: 'สาหร่ายวากาเมะเขียว',
    price: 0,
    category: 'Vegetable',
    type: 'Included',
    image: 'https://images.unsplash.com/photo-1534422298391-e4f8c170db76?w=800&auto=format&fit=crop&q=60',
    allergens: [],
    isVegetarian: true,
    description: 'Fresh green wakame seaweed.',
    descriptionTh: 'สาหร่ายวากาเมะเขียวสด'
  },
  {
    id: 'v3',
    name: 'Shredded Cabbage',
    nameTh: 'กะหล่ำปลีฝอย',
    price: 0,
    category: 'Vegetable',
    type: 'Included',
    image: 'https://images.unsplash.com/photo-1592394533824-9440e5d68530?w=800&auto=format&fit=crop&q=60',
    allergens: [],
    isVegetarian: true,
    description: 'Finely shredded fresh cabbage.',
    descriptionTh: 'กะหล่ำปลีฝอยสดใหม่'
  },
  {
    id: 'v4',
    name: 'Enoki Mushroom',
    nameTh: 'เห็ดเข็มทอง',
    price: 0,
    category: 'Vegetable',
    type: 'Included',
    image: 'https://images.unsplash.com/photo-1581264692575-0d2568019579?w=800&auto=format&fit=crop&q=60',
    allergens: [],
    isVegetarian: true,
    description: 'Fresh and crunchy enoki mushrooms.',
    descriptionTh: 'เห็ดเข็มทองสดกรอบ'
  },
  {
    id: 'v5',
    name: 'Choy Sum',
    nameTh: 'ผักกวางตุ้ง',
    price: 0,
    category: 'Vegetable',
    type: 'Included',
    image: 'https://images.unsplash.com/photo-1587334274328-64186a80aeee?w=800&auto=format&fit=crop&q=60',
    allergens: [],
    isVegetarian: true,
    description: 'Fresh and tender choy sum.',
    descriptionTh: 'ผักกวางตุ้งสดและอ่อน'
  },
  {
    id: 'v6',
    name: 'Chinese Cabbage',
    nameTh: 'ผักกาดขาว',
    price: 0,
    category: 'Vegetable',
    type: 'Included',
    image: 'https://images.unsplash.com/photo-1594313057119-94aa0d4418a2?w=800&auto=format&fit=crop&q=60',
    allergens: [],
    isVegetarian: true,
    description: 'Sweet and crisp Chinese cabbage.',
    descriptionTh: 'ผักกาดขาวรสหวานและกรอบ'
  },
  {
    id: 'v7',
    name: 'Morning Glory',
    nameTh: 'ผักบุ้ง',
    price: 0,
    category: 'Vegetable',
    type: 'Included',
    image: 'https://images.unsplash.com/photo-1540420773420-3366772f4999?w=800&auto=format&fit=crop&q=60',
    allergens: [],
    isVegetarian: true,
    description: 'Fresh water spinach.',
    descriptionTh: 'ผักบุ้งสดใหม่'
  },
  {
    id: 'a1',
    name: 'Gyoza',
    nameTh: 'เกี๊ยวซ่า',
    price: 120,
    category: 'Appetizer',
    type: 'Included',
    image: 'https://images.unsplash.com/photo-1541696432-82c6da8ce7bf?w=800&auto=format&fit=crop&q=60',
    allergens: ['Gluten'],
    isVegetarian: false,
    description: 'Pan-fried Japanese dumplings.',
    descriptionTh: 'เกี๊ยวซ่าญี่ปุ่นทอด'
  },
  {
    id: 'w1',
    name: 'Mineral Water',
    nameTh: 'น้ำแร่',
    price: 25,
    category: 'Water',
    type: 'Included',
    image: 'https://images.unsplash.com/photo-1523362628745-0c100150b504?w=800&auto=format&fit=crop&q=60',
    allergens: [],
    isVegetarian: true,
    description: 'Refreshing chilled mineral water.',
    descriptionTh: 'น้ำแร่เย็นสดชื่น'
  },
  {
    id: 'w2',
    name: 'Green Tea',
    nameTh: 'ชาเขียว',
    price: 45,
    category: 'Water',
    type: 'Included',
    image: 'https://images.unsplash.com/photo-1564890369478-c89ca6d9cde9?w=800&auto=format&fit=crop&q=60',
    allergens: [],
    isVegetarian: true,
    description: 'Premium Japanese green tea, hot or cold.',
    descriptionTh: 'ชาเขียวญี่ปุ่นเกรดพรีเมียม ร้อนหรือเย็น'
  },
  {
    id: 'aso1',
    name: 'Mala Soup',
    nameTh: 'ซุปหมาล่า',
    price: 'xx',
    category: 'Soup',
    type: 'Add-on',
    image: 'https://images.unsplash.com/photo-1547928576-a4a33237ce35?w=800&auto=format&fit=crop&q=60',
    allergens: [],
    isVegetarian: false,
    description: 'Spicy and numbing Sichuan peppercorn broth.',
    descriptionTh: 'ซุปหมาล่ารสชาติเผ็ดร้อนและชาลิ้นสไตล์เสฉวน'
  },
  {
    id: 'aso2',
    name: 'Tom Yum Soup',
    nameTh: 'ซุปต้มยำ',
    price: 'xx',
    category: 'Soup',
    type: 'Add-on',
    image: 'https://images.unsplash.com/photo-1563532724-699395f7f367?w=800&auto=format&fit=crop&q=60',
    allergens: ['Shrimp'],
    isVegetarian: false,
    description: 'Classic Thai spicy and sour soup.',
    descriptionTh: 'ซุปต้มยำรสชาติจัดจ้านแบบไทยแท้'
  },
  {
    id: 'aso3',
    name: 'Traditional Japanese Black Soup',
    nameTh: 'ซุปน้ำดำสไตล์ญี่ปุ่นดั้งเดิม',
    price: 'xx',
    category: 'Soup',
    type: 'Add-on',
    image: 'https://www.mk1642.com/getmetafile/71f006e3-f150-4aaf-ab41-eece52fc3c28/419x260_2.aspx',
    allergens: ['Soy'],
    isVegetarian: true,
    description: 'Authentic premium Japanese sukiyaki broth.',
    descriptionTh: 'ซุปน้ำดำสไตล์ญี่ปุ่นดั้งเดิมเกรดพรีเมียม'
  },
  {
    id: 'aso4',
    name: 'Soy Milk Soup',
    nameTh: 'ซุปน้ำเต้าหู้',
    price: 'xx',
    category: 'Soup',
    type: 'Add-on',
    image: 'https://images.unsplash.com/photo-1526318896980-cf78c088247c?w=800&auto=format&fit=crop&q=60',
    allergens: ['Soy'],
    isVegetarian: true,
    description: 'Creamy and nutritious soy milk broth.',
    descriptionTh: 'ซุปน้ำเต้าหู้รสชาติกลมกล่อมและมีประโยชน์'
  },
  {
    id: 'ao2',
    name: 'Extra Cheese Dip',
    nameTh: 'ชีสดิปพิเศษ',
    price: 50,
    category: 'Appetizer',
    type: 'Add-on',
    image: 'https://images.unsplash.com/photo-1563805042-7684c019e1cb?w=800&auto=format&fit=crop&q=60',
    allergens: ['Dairy'],
    isVegetarian: true,
    description: 'Creamy melted cheese dip for your meat and vegetables.',
    descriptionTh: 'ชีสดิปละลายเข้มข้นสำหรับจิ้มเนื้อและผัก'
  },
  {
    id: 'ao3',
    name: 'Foie Gras Topping',
    nameTh: 'ฟัวกราส์ท็อปปิ้ง',
    price: 250,
    category: 'Meat',
    type: 'Add-on',
    image: 'https://images.unsplash.com/photo-1626645738196-c2a7c8d08f58?w=800&auto=format&fit=crop&q=60',
    allergens: [],
    isVegetarian: false,
    description: 'Seared premium foie gras to top your wagyu.',
    descriptionTh: 'ฟัวกราส์เซียเกรดพรีเมียมสำหรับท็อปบนเนื้อวากิว'
  },
  {
    id: 's1',
    name: 'Durian Sticky Rice Soup',
    nameTh: 'ซุปข้าวเหนียวทุเรียน',
    price: 150,
    category: 'Seasonal',
    type: 'Included',
    image: 'https://images.unsplash.com/photo-1590005354167-6da97870c919?w=800&auto=format&fit=crop&q=60',
    allergens: ['Dairy'],
    isVegetarian: true,
    description: 'Unique seasonal sweet soup with premium Monthong durian.',
    descriptionTh: 'ซุปหวานประจำฤดูกาลที่เป็นเอกลักษณ์ด้วยทุเรียนหมอนทองเกรดพรีเมียม'
  },
  {
    id: 's2',
    name: 'Mango Pomelo Sago',
    nameTh: 'สาคูมะม่วงส้มโอ',
    price: 120,
    category: 'Seasonal',
    type: 'Included',
    image: 'https://images.unsplash.com/photo-1514517604298-cf80e0fb7f1e?w=800&auto=format&fit=crop&q=60',
    allergens: ['Dairy'],
    isVegetarian: true,
    description: 'Refreshing seasonal dessert with fresh mango and pomelo.',
    descriptionTh: 'ของหวานประจำฤดูกาลที่สดชื่นด้วยมะม่วงสดและส้มโอ'
  },
  {
    id: 'rn1',
    name: 'Egg Noodles',
    nameTh: 'บะหมี่หยก',
    price: 0,
    category: 'Rice/Noodle',
    type: 'Included',
    image: 'https://images.unsplash.com/photo-1585032226651-759b368d7246?w=800&auto=format&fit=crop&q=60',
    allergens: ['Gluten', 'Egg'],
    isVegetarian: true,
    description: 'Classic green egg noodles.',
    descriptionTh: 'บะหมี่หยกต้นตำรับ'
  },
  {
    id: 'rn2',
    name: 'Glass Noodles',
    nameTh: 'วุ้นเส้น',
    price: 0,
    category: 'Rice/Noodle',
    type: 'Included',
    image: 'https://images.unsplash.com/photo-1569718212165-3a8278d5f624?w=800&auto=format&fit=crop&q=60',
    allergens: [],
    isVegetarian: true,
    description: 'Clear and chewy glass noodles.',
    descriptionTh: 'วุ้นเส้นเหนียวนุ่ม'
  },
  {
    id: 'rn3',
    name: 'Udon',
    nameTh: 'อุด้ง',
    price: 0,
    category: 'Rice/Noodle',
    type: 'Included',
    image: 'https://images.unsplash.com/photo-1548039927-44707e886d3d?w=800&auto=format&fit=crop&q=60',
    allergens: ['Gluten'],
    isVegetarian: true,
    description: 'Thick Japanese wheat noodles.',
    descriptionTh: 'เส้นอุด้งญี่ปุ่นเหนียวนุ่ม'
  },
  {
    id: 'rn4',
    name: 'Steamed Rice',
    nameTh: 'ข้าวสวย',
    price: 0,
    category: 'Rice/Noodle',
    type: 'Included',
    image: 'https://images.unsplash.com/photo-1516684732162-798a0062be99?w=800&auto=format&fit=crop&q=60',
    allergens: [],
    isVegetarian: true,
    description: 'Premium steamed jasmine rice.',
    descriptionTh: 'ข้าวหอมมะลิคุณภาพดี'
  },
  {
    id: 'rn5',
    name: 'Garlic Fried Rice',
    nameTh: 'ข้าวผัดกระเทียม',
    price: 0,
    category: 'Rice/Noodle',
    type: 'Included',
    image: 'https://images.unsplash.com/photo-1603133872878-684f208fb84b?w=800&auto=format&fit=crop&q=60',
    allergens: ['Soy'],
    isVegetarian: true,
    description: 'Fragrant fried rice with golden garlic.',
    descriptionTh: 'ข้าวผัดกระเทียมหอมกรุ่น'
  },
  {
    id: 'd1',
    name: 'Taro in Coconut Milk',
    nameTh: 'เผือกต้มน้ำกะทิ',
    price: 0,
    category: 'Dessert',
    type: 'Included',
    image: 'https://images.unsplash.com/photo-1590080875515-8a3a8dc5735e?w=800&auto=format&fit=crop&q=60',
    allergens: [],
    isVegetarian: true,
    description: 'Sweet taro in warm coconut milk.',
    descriptionTh: 'เผือกนุ่มในน้ำกะทิหอมหวาน'
  },
  {
    id: 'd2',
    name: 'Ginkgo Nut in Fresh Milk',
    nameTh: 'แปะก๊วยนมสด',
    price: 0,
    category: 'Dessert',
    type: 'Included',
    image: 'https://images.unsplash.com/photo-1563805042-7684c019e1cb?w=800&auto=format&fit=crop&q=60',
    allergens: ['Milk'],
    isVegetarian: true,
    description: 'Healthy ginkgo nuts in fresh milk.',
    descriptionTh: 'แปะก๊วยบำรุงสมองในนมสด'
  },
  {
    id: 'd3',
    name: 'Snow Ice with Toppings',
    nameTh: 'น้ำแข็งใส',
    price: 0,
    category: 'Dessert',
    type: 'Included',
    image: 'https://images.unsplash.com/photo-1551024601-bec78aea704b?w=800&auto=format&fit=crop&q=60',
    allergens: [],
    isVegetarian: true,
    description: 'Refreshing snow ice with assorted toppings.',
    descriptionTh: 'น้ำแข็งใสสดชื่นพร้อมเครื่องเคียง'
  },
  {
    id: 'd4',
    name: 'Seasonal Fruit',
    nameTh: 'ผลไม้ตามฤดูกาล',
    price: 0,
    category: 'Dessert',
    type: 'Included',
    image: 'https://images.unsplash.com/photo-1619566636858-adf3ef46400b?w=800&auto=format&fit=crop&q=60',
    allergens: [],
    isVegetarian: true,
    description: 'Freshly sliced seasonal fruits.',
    descriptionTh: 'ผลไม้สดตามฤดูกาล'
  },
];

export const PROMOTION_BASE_PRICE = 299;

export const STARTER_SET: MenuItem[] = [
  MENU_ITEMS.find(i => i.id === 'b1')!,
  MENU_ITEMS.find(i => i.id === 'm2')!,
  MENU_ITEMS.find(i => i.id === 'v6')!,
];
